#!/bin/csh

#set USEDIR=./_output/
set USEDIR=./_output_1600cells

xmgrace -block $USEDIR/gauge00001.txt -bxy 2:6 \
     -block $USEDIR/gauge00002.txt -bxy 2:6  \
     -block $USEDIR/gauge00003.txt -bxy 2:6  \
     -block $USEDIR/gauge00004.txt -bxy 2:6  \
     -block $USEDIR/gauge00005.txt -bxy 2:6  \
     -block $USEDIR/gauge00006.txt -bxy 2:6  \
     -block $USEDIR/gauge00007.txt -bxy 2:6  \
     -block $USEDIR/gauge00008.txt -bxy 2:6  \
     -block $USEDIR/gauge00009.txt -bxy 2:6  \
     -block $USEDIR/gauge00010.txt -bxy 2:6  \
     -block $USEDIR/gauge00021.txt -bxy 2:6  \
     -block $USEDIR/gauge00022.txt -bxy 2:6  \
     -block $USEDIR/gauge00023.txt -bxy 2:6  \
     -block $USEDIR/gauge00024.txt -bxy 2:6  \
     -block $USEDIR/gauge00025.txt -bxy 2:6  \
     -block $USEDIR/gauge00026.txt -bxy 2:6  \
     -block $USEDIR/gauge00027.txt -bxy 2:6  \
     -block $USEDIR/gauge00028.txt -bxy 2:6  \
     -block $USEDIR/gauge00029.txt -bxy 2:6  \
     -block $USEDIR/gauge00030.txt -bxy 2:6   -par gauge.par -free -noask   &

